In [1]:
print(0)

0


In [2]:
import pandas as pd 

In [3]:
df=pd.read_csv('test.csv')

In [4]:
df

,Review,Label
0,Great CD: My lovely Pat has one of the GREAT v...,2
1,One of the best game music soundtracks - for a...,2
2,Batteries died within a year ...: I bought thi...,1
3,"works fine, but Maha Energy is better: Check o...",2
4,Great for the non-audiophile: Reviewed quite a...,2
...,...,...
399995,Unbelievable- In a Bad Way: We bought this Tho...,1
399996,"Almost Great, Until it Broke...: My son reciev...",1
399997,Disappointed !!!: I bought this toy for my son...,1
399998,Classic Jessica Mitford: This is a compilation...,2


In [5]:
df.head()

,Review,Label
0,Great CD: My lovely Pat has one of the GREAT v...,2
1,One of the best game music soundtracks - for a...,2
2,Batteries died within a year ...: I bought thi...,1
3,"works fine, but Maha Energy is better: Check o...",2
4,Great for the non-audiophile: Reviewed quite a...,2


In [6]:
df=df[['Review','Label']]
df.shape

(400000, 2)

In [7]:
df.isnull().sum()

Review    0
Label     0
dtype: int64

In [8]:
df['Label'].unique()
df['Label'].value_counts()

Label
2    200000
1    200000
Name: count, dtype: int64

In [9]:
#preprocessing and cleaning 
df['Label'] = df['Label'].apply(lambda x: 0 if x == 1 else 1)

In [10]:
df.head()

,Review,Label
0,Great CD: My lovely Pat has one of the GREAT v...,1
1,One of the best game music soundtracks - for a...,1
2,Batteries died within a year ...: I bought thi...,0
3,"works fine, but Maha Energy is better: Check o...",1
4,Great for the non-audiophile: Reviewed quite a...,1


In [11]:
df['Label'].unique()
df['Label'].value_counts()

Label
1    200000
0    200000
Name: count, dtype: int64

In [12]:
# lowercase all 
df['Review']=df['Review'].str.lower()

In [13]:
df

,Review,Label
0,great cd: my lovely pat has one of the great v...,1
1,one of the best game music soundtracks - for a...,1
2,batteries died within a year ...: i bought thi...,0
3,"works fine, but maha energy is better: check o...",1
4,great for the non-audiophile: reviewed quite a...,1
...,...,...
399995,unbelievable- in a bad way: we bought this tho...,0
399996,"almost great, until it broke...: my son reciev...",0
399997,disappointed !!!: i bought this toy for my son...,0
399998,classic jessica mitford: this is a compilation...,1


In [14]:
## clean the data removing special char 
import re
import nltk
from nltk.corpus import stopwords

# Download stopwords once
# nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def clean_text(text):
    # Make sure input is string
    text = str(text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)

    # Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', ' ', text)

    # Convert to lowercase
    text = text.lower()

    # Remove special characters and numbers
    text = re.sub(r'[^a-zA-Z\s]', ' ', text)

    # Remove stopwords
    text = ' '.join(
        word for word in text.split()
        if word not in stop_words
    )

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text


# Apply cleaning
df['Review'] = df['Review'].apply(clean_text)

# Check result
# print(df[['Review', 'Clean_Review']].head())


In [15]:
df

,Review,Label
0,great cd lovely pat one great voices generatio...,1
1,one best game music soundtracks game really pl...,1
2,batteries died within year bought charger jul ...,0
3,works fine maha energy better check maha energ...,1
4,great non audiophile reviewed quite bit combo ...,1
...,...,...
399995,unbelievable bad way bought thomas son huge th...,0
399996,almost great broke son recieved birthday gift ...,0
399997,disappointed bought toy son loves thomas toys ...,0
399998,classic jessica mitford compilation wide range...,1


In [16]:
#lemmatizer 
from nltk.stem import WordNetLemmatizer

In [17]:
print(type(df['Review'].iloc[0]))
print(df['Review'].iloc[0])

<class 'str'>
great cd lovely pat one great voices generation listened cd years still love good mood makes feel better bad mood evaporates like sugar rain cd oozes life vocals jusat stuunning lyrics kill one life hidden gems desert isle cd book never made big beyond everytime play matter black white young old male female everybody says one thing singing


In [18]:
from nltk.stem import WordNetLemmatizer
import nltk

nltk.download('wordnet')

lemma = WordNetLemmatizer()

def lemmatizer(text):
    return " ".join([lemma.lemmatize(word) for word in text.split()])

df['Review'] = df['Review'].apply(lambda x: lemmatizer(x))

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\dipes\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [19]:
df.head()

,Review,Label
0,great cd lovely pat one great voice generation...,1
1,one best game music soundtrack game really pla...,1
2,battery died within year bought charger jul wo...,0
3,work fine maha energy better check maha energy...,1
4,great non audiophile reviewed quite bit combo ...,1


In [20]:
x = df['Review']
y=df['Label']

In [21]:
x,y


(0         great cd lovely pat one great voice generation...
 1         one best game music soundtrack game really pla...
 2         battery died within year bought charger jul wo...
 3         work fine maha energy better check maha energy...
 4         great non audiophile reviewed quite bit combo ...
                                 ...                        
 399995    unbelievable bad way bought thomas son huge th...
 399996    almost great broke son recieved birthday gift ...
 399997    disappointed bought toy son love thomas toy ne...
 399998    classic jessica mitford compilation wide range...
 399999    comedy scene heard dvd disappointment get hopi...
 Name: Review, Length: 400000, dtype: str,
 0         1
 1         1
 2         0
 3         1
 4         1
          ..
 399995    0
 399996    0
 399997    0
 399998    1
 399999    0
 Name: Label, Length: 400000, dtype: int64)

In [22]:
from sklearn.model_selection import train_test_split

xtr,xte,ytr,yte=train_test_split(x,y,test_size=0.25,random_state=42)

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer(
    max_features=50000,
    min_df=2,
    max_df=0.95
)

xtr_bow = bow.fit_transform(xtr)
xte_bow = bow.transform(xte)

print("Train:", xtr_bow.shape)
print("Test:", xte_bow.shape)

Train: (300000, 50000)
Test: (100000, 50000)


In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=50000,
    min_df=2,
    max_df=0.95
)

xtr_tfidf = tfidf.fit_transform(xtr)
xte_tfidf = tfidf.transform(xte)

print("Train:", xtr_tfidf.shape)
print("Test:", xte_tfidf.shape)

Train: (300000, 50000)
Test: (100000, 50000)


In [32]:
xtr_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 9861794 stored elements and shape (300000, 50000)>

In [38]:
from sklearn.naive_bayes import MultinomialNB
mb=MultinomialNB()

In [ ]:
bow_mb=mb.fit(xtr_bow,ytr)
tf_mb=mb.fit(xtr_tfidf,ytr)

In [44]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
ypred_bow=mb.predict(xte_bow)
ypred_tf=mb.predict(xte_tfidf)

In [50]:
%pip install gensim

  Using cached smart_open-8.0.1-py3-none-any.whl.metadata (24 kB)
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   - -------------------------------------- 0.8/24.4 MB 3.7 MB/s eta 0:00:07
   -- ------------------------------------- 1.3/24.4 MB 3.4 MB/s eta 0:00:07
   --- ------------------------------------ 1.8/24.4 MB 3.1 MB/s eta 0:00:08
   ---- ----------------------------------- 2.6/24.4 MB 3.0 MB/s eta 0:00:08
   ----- ---------------------------------- 3.1/24.4 MB 2.9 MB/s eta 0:00:08
   ------ --------------------------------- 3.9/24.4 MB 2.8 MB/s eta 0:00:08
   ------- -------------------------------- 4.5/24.4 MB 2.8 MB/s eta 0:00:08
   -------- ------------------------------- 5.2/24.4 MB 2.7 MB/s eta 0:00:07
   --------- ------------------------------ 5.8/24.4 MB 2.7 MB/s eta 0:00:07
   ---------- ----------------------------- 6.6/24.4 MB 2.7 MB/s eta 0:00:07
   ------------ --------------------------- 7.9/24.4 MB 2.7 MB/s eta 0:00:07
   ------------- 

In [51]:
from gensim.models import Word2Vec


In [47]:
print("BOW",accuracy_score(ypred_bow,yte))
print(confusion_matrix(ypred_bow,yte))
print(classification_report(ypred_bow,yte))

BOW 0.85177
[[42325  7135]
 [ 7688 42852]]
              precision    recall  f1-score   support

           0       0.85      0.86      0.85     49460
           1       0.86      0.85      0.85     50540

    accuracy                           0.85    100000
   macro avg       0.85      0.85      0.85    100000
weighted avg       0.85      0.85      0.85    100000



In [48]:
print("TF-IDF",accuracy_score(ypred_tf,yte))
print(confusion_matrix(ypred_tf,yte))
print(classification_report(ypred_tf,yte))

TF-IDF 0.83969
[[42251  8269]
 [ 7762 41718]]
              precision    recall  f1-score   support

           0       0.84      0.84      0.84     50520
           1       0.83      0.84      0.84     49480

    accuracy                           0.84    100000
   macro avg       0.84      0.84      0.84    100000
weighted avg       0.84      0.84      0.84    100000



In [52]:
from gensim.models import Word2Vec

# Tokenize reviews
sentences = [review.split() for review in xtr]

# Train Word2Vec
w2v = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

In [53]:
import numpy as np

def document_vector(review, model):
    words = review.split()
    
    vectors = [
        model.wv[word]
        for word in words
        if word in model.wv
    ]
    
    if len(vectors) == 0:
        return np.zeros(model.vector_size)
    
    return np.mean(vectors, axis=0)

In [54]:
xtr_w2v = np.array([
    document_vector(review, w2v)
    for review in xtr
])

xte_w2v = np.array([
    document_vector(review, w2v)
    for review in xte
])

In [55]:
print(xtr_w2v.shape)
print(xte_w2v.shape)

(300000, 100)
(100000, 100)


In [56]:
from sklearn.linear_model import LogisticRegression

w2v_model = LogisticRegression(max_iter=1000)

w2v_model.fit(xtr_w2v, ytr)

y_pred = w2v_model.predict(xte_w2v)

In [57]:
print(accuracy_score(yte, y_pred))

0.86114


In [58]:
len(w2v.wv)

87976

In [59]:
w2v.wv["good"]

array([-1.9371707 , -0.0248465 , -0.5630147 , -0.9373126 ,  1.8281399 ,
       -0.723268  , -0.03020606, -0.50821686, -1.1546317 ,  1.7206962 ,
       -1.2680681 ,  3.5200372 , -0.67586285, -0.7764834 ,  0.54464465,
        0.08056401,  0.57732815,  2.2182815 , -0.07976609,  1.4334692 ,
        0.18039088, -1.966719  , -0.5174905 , -2.0564005 ,  0.19687334,
        0.15478736,  0.5106594 ,  0.2845699 , -0.998807  ,  2.9608502 ,
        0.07083686,  0.87733185, -3.6225162 , -0.5067267 ,  0.8575669 ,
       -0.39971706, -0.14630277,  0.5913066 , -1.0558008 ,  0.43060324,
       -0.5773901 ,  2.3293438 , -2.1107008 ,  1.5000103 ,  0.5193331 ,
        0.06864149,  1.1298838 ,  0.06336574,  1.3134774 , -0.05056804,
       -0.4631294 , -0.80119425,  1.630376  , -0.5151567 , -0.49446478,
        0.32830405, -1.1631888 , -0.38833204, -0.5051625 , -1.9481565 ,
        1.3578414 ,  0.9050144 , -0.26958528, -0.80777514, -0.04145841,
        1.011069  ,  3.2943358 , -0.7104902 ,  0.9617764 , -0.50

In [60]:
w2v.wv.most_similar("good")

[('great', 0.7955518960952759),
 ('decent', 0.7778087854385376),
 ('bad', 0.7062351107597351),
 ('ok', 0.6823132038116455),
 ('nice', 0.676384687423706),
 ('okay', 0.631120502948761),
 ('excellent', 0.6221439838409424),
 ('awesome', 0.5612651109695435),
 ('fine', 0.5523089170455933),
 ('like', 0.5504378080368042)]

In [61]:
import numpy as np

def predict_review(review, w2v, model):
    # Convert review into Word2Vec document vector
    vector = document_vector(review, w2v)

    # ML model expects 2D input: (1, 100)
    vector = vector.reshape(1, -1)

    # Make prediction
    prediction = model.predict(vector)

    return prediction[0]

In [63]:
new_review = "This product is amazing and I really love it"

prediction = predict_review(new_review, w2v, w2v_model)

print(prediction)

1


In [66]:
def predict_review(review, w2v, model):
    vector = document_vector(review, w2v)
    vector = vector.reshape(1, -1)

    prediction = model.predict(vector)[0]
    probability = model.predict_proba(vector)[0]

    return prediction, probability

prediction, probability = predict_review(
    "The product is excellent",
    w2v,
    w2v_model
)

print("Prediction:", prediction)
print("Probability:", probability)

Prediction: 1
Probability: [9.92007229e-08 9.99999901e-01]
